name: portable_sec
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.32

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^3.1.0
  riverpod_annotation: ^4.0.0
  nfc_toolkit:
    path: ./packages/nfc_toolkit
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.1.0
  encrypt: ^5.0.3
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  freezed: ^3.2.3
  shared_preferences: ^2.5.4
  json_annotation: ^4.9.0
  crypto: ^3.0.7
  go_router: ^17.0.1
  url_launcher: ^6.3.2
  package_info_plus: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  riverpod_generator: ^4.0.0+1
  json_serializable: ^6.11.2
  mockito: ^5.6.3

flutter:
  uses-material-design: true
  assets:
   - assets/
